// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.0-devel
// 	protoc        v4.25.1
// source: internal/bsr/proto/postgres/v1/postgres_chunks.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataChunk is a raw byte chunk for unparsed or non-auditable PostgreSQL messages.
type DataChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The raw bytes of the PostgreSQL wire protocol message.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The direction the message was travelling when recorded.
	// "up" = client to backend; "down" = backend to client.
	Direction string `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescGZIP(), []int{0}
}

func (x *DataChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataChunk) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

// StartupChunk contains sanitized startup message parameters.
// Credentials (password) are consumed by the proxy and not stored here.
type StartupChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The user connecting to the database.
	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// The database being connected to.
	Database string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	// Additional startup parameters (application_name, client_encoding, etc.).
	Options map[string]string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *StartupChunk) Reset() {
	*x = StartupChunk{}
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartupChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartupChunk) ProtoMessage() {}

func (x *StartupChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartupChunk.ProtoReflect.Descriptor instead.
func (*StartupChunk) Descriptor() ([]byte, []int) {
	return file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescGZIP(), []int{1}
}

func (x *StartupChunk) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *StartupChunk) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *StartupChunk) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

// AuthChunk contains the authentication method and outcome.
type AuthChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The authentication method used.
	// One of: "cleartext", "md5", "scram-sha-256", "unspecified".
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// Whether authentication succeeded.
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if authentication failed.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AuthChunk) Reset() {
	*x = AuthChunk{}
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthChunk) ProtoMessage() {}

func (x *AuthChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthChunk.ProtoReflect.Descriptor instead.
func (*AuthChunk) Descriptor() ([]byte, []int) {
	return file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescGZIP(), []int{2}
}

func (x *AuthChunk) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuthChunk) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// QueryChunk contains a simple SQL query from a client Query message.
type QueryChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The SQL query string.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// The database this query was run against.
	Database string `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
}

func (x *QueryChunk) Reset() {
	*x = QueryChunk{}
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChunk) ProtoMessage() {}

func (x *QueryChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChunk.ProtoReflect.Descriptor instead.
func (*QueryChunk) Descriptor() ([]byte, []int) {
	return file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescGZIP(), []int{3}
}

func (x *QueryChunk) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryChunk) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

// ParseChunk contains a prepared statement parse message from the client.
type ParseChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the prepared statement.
	StatementName string `protobuf:"bytes,1,opt,name=statement_name,json=statementName,proto3" json:"statement_name,omitempty"`
	// The SQL query string for the prepared statement.
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// The database this statement was parsed against.
	Database string `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
}

func (x *ParseChunk) Reset() {
	*x = ParseChunk{}
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseChunk) ProtoMessage() {}

func (x *ParseChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseChunk.ProtoReflect.Descriptor instead.
func (*ParseChunk) Descriptor() ([]byte, []int) {
	return file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescGZIP(), []int{4}
}

func (x *ParseChunk) GetStatementName() string {
	if x != nil {
		return x.StatementName
	}
	return ""
}

func (x *ParseChunk) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ParseChunk) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

// BindChunk contains a bind message with parameter values.
// Uses the resolved SQL from a prior ParseChunk by statement name.
type BindChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the prepared statement to execute.
	StatementName string `protobuf:"bytes,1,opt,name=statement_name,json=statementName,proto3" json:"statement_name,omitempty"`
	// The name of the portal to create.
	PortalName string `protobuf:"bytes,2,opt,name=portal_name,json=portalName,proto3" json:"portal_name,omitempty"`
	// The resolved SQL query from the named prepared statement.
	Query string `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	// Parameter values provided by the client.
	ParamValues [][]byte `protobuf:"bytes,4,rep,name=param_values,json=paramValues,proto3" json:"param_values,omitempty"`
	// Parameter type OIDs (PostgreSQL type system).
	ParamTypes []uint32 `protobuf:"varint,5,rep,packed,name=param_types,json=paramTypes,proto3" json:"param_types,omitempty"`
	// The database this bind was issued against.
	Database string `protobuf:"bytes,6,opt,name=database,proto3" json:"database,omitempty"`
}

func (x *BindChunk) Reset() {
	*x = BindChunk{}
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindChunk) ProtoMessage() {}

func (x *BindChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindChunk.ProtoReflect.Descriptor instead.
func (*BindChunk) Descriptor() ([]byte, []int) {
	return file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescGZIP(), []int{5}
}

func (x *BindChunk) GetStatementName() string {
	if x != nil {
		return x.StatementName
	}
	return ""
}

func (x *BindChunk) GetPortalName() string {
	if x != nil {
		return x.PortalName
	}
	return ""
}

func (x *BindChunk) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *BindChunk) GetParamValues() [][]byte {
	if x != nil {
		return x.ParamValues
	}
	return nil
}

func (x *BindChunk) GetParamTypes() []uint32 {
	if x != nil {
		return x.ParamTypes
	}
	return nil
}

func (x *BindChunk) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

// BindResponseChunk is the backend's response to a Bind message.
type BindResponseChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// True if the bind succeeded.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if the bind failed.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *BindResponseChunk) Reset() {
	*x = BindResponseChunk{}
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindResponseChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindResponseChunk) ProtoMessage() {}

func (x *BindResponseChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindResponseChunk.ProtoReflect.Descriptor instead.
func (*BindResponseChunk) Descriptor() ([]byte, []int) {
	return file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescGZIP(), []int{6}
}

func (x *BindResponseChunk) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BindResponseChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ExecuteChunk contains an execute message specifying which portal to run.
type ExecuteChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the portal to execute.
	PortalName string `protobuf:"bytes,1,opt,name=portal_name,json=portalName,proto3" json:"portal_name,omitempty"`
	// Maximum number of rows to return (0 = all rows).
	MaxRows uint32 `protobuf:"varint,2,opt,name=max_rows,json=maxRows,proto3" json:"max_rows,omitempty"`
}

func (x *ExecuteChunk) Reset() {
	*x = ExecuteChunk{}
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteChunk) ProtoMessage() {}

func (x *ExecuteChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteChunk.ProtoReflect.Descriptor instead.
func (*ExecuteChunk) Descriptor() ([]byte, []int) {
	return file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteChunk) GetPortalName() string {
	if x != nil {
		return x.PortalName
	}
	return ""
}

func (x *ExecuteChunk) GetMaxRows() uint32 {
	if x != nil {
		return x.MaxRows
	}
	return 0
}

// ExecuteResponseChunk is the backend's response to an Execute message.
type ExecuteResponseChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of rows processed (INSERT/UPDATE/DELETE) or returned (SELECT).
	RowsAffected int64 `protobuf:"varint,1,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	// True if execution resulted in an error.
	Error bool `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	// Error message if execution failed.
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *ExecuteResponseChunk) Reset() {
	*x = ExecuteResponseChunk{}
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponseChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponseChunk) ProtoMessage() {}

func (x *ExecuteResponseChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponseChunk.ProtoReflect.Descriptor instead.
func (*ExecuteResponseChunk) Descriptor() ([]byte, []int) {
	return file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteResponseChunk) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *ExecuteResponseChunk) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *ExecuteResponseChunk) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ParseCompleteChunk indicates a Parse message was successfully processed.
type ParseCompleteChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ParseCompleteChunk) Reset() {
	*x = ParseCompleteChunk{}
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseCompleteChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseCompleteChunk) ProtoMessage() {}

func (x *ParseCompleteChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseCompleteChunk.ProtoReflect.Descriptor instead.
func (*ParseCompleteChunk) Descriptor() ([]byte, []int) {
	return file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescGZIP(), []int{9}
}

// SyncChunk indicates a Sync message, ending an implicit transaction block.
type SyncChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncChunk) Reset() {
	*x = SyncChunk{}
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChunk) ProtoMessage() {}

func (x *SyncChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChunk.ProtoReflect.Descriptor instead.
func (*SyncChunk) Descriptor() ([]byte, []int) {
	return file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescGZIP(), []int{10}
}

// ErrorChunk contains a PostgreSQL ErrorResponse.
type ErrorChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Severity: ERROR, FATAL, PANIC, WARNING, NOTICE, etc.
	Severity string `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	// SQLSTATE code.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// Human-readable error message.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Additional detail (optional).
	Detail string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	// Hint (optional).
	Hint string `protobuf:"bytes,5,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *ErrorChunk) Reset() {
	*x = ErrorChunk{}
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorChunk) ProtoMessage() {}

func (x *ErrorChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorChunk.ProtoReflect.Descriptor instead.
func (*ErrorChunk) Descriptor() ([]byte, []int) {
	return file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescGZIP(), []int{11}
}

func (x *ErrorChunk) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ErrorChunk) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorChunk) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorChunk) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ErrorChunk) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

// DoneChunk indicates normal session termination.
type DoneChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The reason for termination.
	// One of: "normal", "client_disconnect", "server_disconnect", "timeout".
	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *DoneChunk) Reset() {
	*x = DoneChunk{}
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoneChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoneChunk) ProtoMessage() {}

func (x *DoneChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoneChunk.ProtoReflect.Descriptor instead.
func (*DoneChunk) Descriptor() ([]byte, []int) {
	return file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescGZIP(), []int{12}
}

func (x *DoneChunk) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_internal_bsr_proto_postgres_v1_postgres_chunks_proto protoreflect.FileDescriptor

var file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDesc = []byte{
	0x0a, 0x34, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x62, 0x73, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2f, 0x76, 0x31,
	0x2f, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x22, 0x3d, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0xbc, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x75, 0x70, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x2e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x53, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x3e, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x22, 0x65, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x73, 0x65, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x22, 0xc9, 0x01,
	0x0a, 0x09, 0x42, 0x69, 0x6e, 0x64, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x25, 0x0a, 0x0e, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x0b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x22, 0x43, 0x0a, 0x11, 0x42, 0x69, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x4a,
	0x0a, 0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x52, 0x6f, 0x77, 0x73, 0x22, 0x76, 0x0a, 0x14, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x6f, 0x77, 0x73, 0x5f, 0x61, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x72, 0x6f, 0x77, 0x73, 0x41,
	0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x23, 0x0a,
	0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x50, 0x61, 0x72, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x0b, 0x0a, 0x09, 0x53, 0x79, 0x6e, 0x63,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x82, 0x01, 0x0a, 0x0a, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x22, 0x23, 0x0a, 0x09, 0x44, 0x6f,
	0x6e, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42,
	0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x61,
	0x73, 0x68, 0x69, 0x63, 0x6f, 0x72, 0x70, 0x2f, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x72, 0x79,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x62, 0x73, 0x72, 0x2f, 0x67, 0x65,
	0x6e, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescOnce sync.Once
	file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescData = file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDesc
)

func file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescGZIP() []byte {
	file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescOnce.Do(func() {
		file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescData)
	})
	return file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDescData
}

var file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_goTypes = []any{
	(*DataChunk)(nil),            // 0: postgres.v1.DataChunk
	(*StartupChunk)(nil),         // 1: postgres.v1.StartupChunk
	(*AuthChunk)(nil),            // 2: postgres.v1.AuthChunk
	(*QueryChunk)(nil),           // 3: postgres.v1.QueryChunk
	(*ParseChunk)(nil),           // 4: postgres.v1.ParseChunk
	(*BindChunk)(nil),            // 5: postgres.v1.BindChunk
	(*BindResponseChunk)(nil),    // 6: postgres.v1.BindResponseChunk
	(*ExecuteChunk)(nil),         // 7: postgres.v1.ExecuteChunk
	(*ExecuteResponseChunk)(nil), // 8: postgres.v1.ExecuteResponseChunk
	(*ParseCompleteChunk)(nil),   // 9: postgres.v1.ParseCompleteChunk
	(*SyncChunk)(nil),            // 10: postgres.v1.SyncChunk
	(*ErrorChunk)(nil),           // 11: postgres.v1.ErrorChunk
	(*DoneChunk)(nil),            // 12: postgres.v1.DoneChunk
	nil,                          // 13: postgres.v1.StartupChunk.OptionsEntry
}
var file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_depIdxs = []int32{
	13, // 0: postgres.v1.StartupChunk.options:type_name -> postgres.v1.StartupChunk.OptionsEntry
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_init() }
func file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_init() {
	if File_internal_bsr_proto_postgres_v1_postgres_chunks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_goTypes,
		DependencyIndexes: file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_depIdxs,
		MessageInfos:      file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_msgTypes,
	}.Build()
	File_internal_bsr_proto_postgres_v1_postgres_chunks_proto = out.File
	file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_rawDesc = nil
	file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_goTypes = nil
	file_internal_bsr_proto_postgres_v1_postgres_chunks_proto_depIdxs = nil
}
